### ISSUE TITLE
Blank output

### ISSUE THREAD

**Issue by aviks** [shashi/Canvas.jl#4] opened 2015-03-29 09:16 UTC
So, doing everything mentioned in #3 removes all error messages. However, then navigating to, for eg. http://localhost:8000/examples/toolbar.jl shows a blank page in the browser. 

View source in the browser shows: https://gist.github.com/aviks/16e883c1ac50662a5a02

Resources fetched in the browser as follows: 

![screen shot 2015-03-29 at 10 14 39](https://cloud.githubusercontent.com/assets/378918/6884853/772b9f6e-d5fc-11e4-8a71-e9ff5ddd8212.png)

So what can I do to troubleshoot this further? 

PS: did I  say it already... hugely excited about Canvas.jl!!

**Comment by shashi** [comment] 2015-03-29 09:21
What does the JS Console say? (Apart from undefined var IPython.) I have *never* yet tried this in Firefox! It does work in Chrome right?

I think, I need to use `Polymer.import` which should in turn use the polyfill on Firefox which should mean that setting the flag won't be necessary.

**Comment by aviks** [comment] 2015-03-29 09:30
No, it does not work in Chrome :(. I am in exactly the same state in Chrome and FF. 

JS console only has the IPython error. Clean otherwise.

**Comment by aviks** [comment] 2015-03-29 10:14
I get the feeling that I am not picking up the right code. 

So am navigating to `http://localhost:8000/examples/toolbar.jl`. If I navigate to `http://localhost:8000/foo/bar.jl`, I also get a blank page with no errors. The returned html is similar, but with `new Canvasd("examples", "root")` replaced by `new Canvasd("foo", "root")`. 

Is that what I'd expect? How can I verify that the code in `<Pkg.dir/Canvas.jl>/examples/toolbar.jl` is being executed?

**Comment by shashi** [comment] 2015-03-29 10:36
I think I know what the problem is, it's to do with me not closing an html tag somewhere, hold on.

**Comment by shashi** [comment] 2015-03-29 10:43
You need to run canvasd from examples/. and go to http://localhost:8000/toolbar.jl `foo/bar.jl` should ideally work, I'll look into it.

**Comment by shashi** [comment] 2015-03-29 11:23
@aviks Any luck if you run it from examples/? I am not sure yet why it is not showing the error indicating the file doesn't exist.

@one-more-minute what is a good way to get the full path?

**Comment by aviks** [comment] 2015-03-29 11:25
OK, perfect, thanks. It works if I run canvasd from the `examples` directory. Thanks!

It works as expected in Chrome, and loads in Firefox. But FF seem to not load the CSS. I'll file a separate issue for that.

**Comment by shashi** [comment] 2015-03-29 11:26
Okay, great! I'm very stoked to have you give Canvas a try :)

**Comment by aviks** [comment] 2015-03-29 11:44
Thanks. I have Great Expectations from Canvas!

**Closed** 2015-03-30 21:50 UTC
